name: Datapipeline Test

on:
  push:
    branches:
    - main
    paths:
    - project/**
    - data/**

jobs:
  project-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: main

    # Install python
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    # Install required Python packages
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    # Run project tests
    - name: Run tests
      run: |
        ./project/tests.sh
